### ISSUE TITLE
"Unable to get path for object ID"

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/searchfs#1]
> (snip)
> /Applications/iTunes.app/Contents/MacOS/iTunesHelper.app
> **Unable to get path for object ID: 3430632Unable to get path for object ID: 3460180/Applications/Video/Adapter.app**
> /Applications/Video/MediaInfo.app
> (snip)

This happens multiple times in the results, for different object IDs.

Let me know if/how I can provide more logging or diagnostics.

**Comment by sveinbjornt** [comment]
I'm still working on this tool so it's a bit rough around the edges, and has really only been tested on my system (10.13.4, with APFS).

What version of macOS are you running, and are you using APFS? 

Btw, the binary available for download is out of date. To use the latest version, clone the git repo, and do make, and then make install.

**Comment by gingerbeardman** [comment]
Same, 10.13.4 and APFS on an SSD.

Will build source and retest.

**Comment by gingerbeardman** [comment]
FYI still happens with latest source build

> Unable to get path for object ID: 12646174
