### ISSUE TITLE
Only scan a specific directory?

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/searchfs#2]
one of my common workflow scripts searches for all **.app** files in **/Applications** and then processes them.

Currently I do this:

`mdfind -onlyin /Applications "kMDItemFSName == *.app"`
> real	0m1.009s
> user	0m0.023s
> sys	0m0.027s

an slower alternative would be:

`find "/Applications" -iname "*.app" -exec echo {} \;`
> real	1m20.565s
> user	0m6.577s
> sys	0m29.990s

however `searchfs` is even slower than this as i have to scan the whole volume and filter the results:

`searchfs ".app" | grep -E "^/Applications.+app$"`
> real	2m7.277s
> user	0m0.108s
> sys	0m46.177s

So it would be useful if `searchfs` could operate on the `cwd` or a directory passed as an `argv`?

**Comment by sveinbjornt** [comment]
Since searchfs uses the file system catalog, it completely ignores the folder structure on the volume and thus cannot search within individual directories. Its only use case is for searching the *entire* volume.

**Comment by gingerbeardman** [comment]
Time for latest build

> real	2m5.121s
> user	0m0.100s
> sys	0m45.475s
