### ISSUE TITLE
Support other file systems?

### ISSUE THREAD

**Issue by dufferzafar** [sveinbjornt/searchfs#4]
_This is not really a "issue", and I realise that it's not even a feature request, but I still wanted to discuss the possibilities._

Is it possible to add support for other file systems? 

Are there any other file systems which have Catalog of files? I guess NTFS does. (as [Everything](http://voidtools.com/) uses it for search)

But do you know if ext3/4 or any other linux file systems have this?

**Comment by dufferzafar** [comment]
There are a lot of tools that try to improve upon search times in Linux land, `locate` is the most famous of them. Which just crawls the entire disk, builds a single database, on which future searches can happen. Updating the database takes ~40 seconds on my machine (and is done at every boot i think.) 

If it is even possible, a faster way would be to sift through the file catalog to build a database (this is what Everything does on NTFS.)

**Comment by sveinbjornt** [comment]
searchfs is intended for use on macOS systems, which typically use either HFS+ or AFPS. The entire point is that it does not perform indexing but rather a live search of the filesystem catalogue. Building a locate-style database and searching it would be a different project altogether, though such a catalogue could certainly be built quickly using searchfs.
